FROM node:22-alpine

# Define a pasta de trabalho
WORKDIR /app

# Copia apenas os arquivos de dependência primeiro
COPY package*.json ./

# Instala as dependências
RUN npm install

# Libera a porta do Vite
EXPOSE 5173

# Roda o servidor de desenvolvimento do Vite
CMD ["npm", "run", "dev"]